# Generated by Django 5.1.15 on 2026-02-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('visible', models.BooleanField(default=False)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('legend_url', models.TextField(blank=True, default='', null=True)),
                ('attribution_source', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('attribution_license', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('attribution_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublayers', to='frontend_config.maplayer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='frontend_config.maplayergroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_display_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configurations',
                'unique_together': {('app_label', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ModelFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='frontend_config.modelconfig')),
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'unique_together': {('model_config', 'field_name')},
            },
        ),
    ]
