pipelines:
  - name: KL_EVENTS
    cron_expression: "0 1 * * *"
  - name: KL_EVENTS_RIS
    cron_expression: "1 1 * * *"
  - name: WGA_EVENTS
    cron_expression: "2 1 * * *"
  - name: TTN_GATEWAY
    cron_expression: "3 1 * * *"
  - name: WIFI_FREIFUNK
    cron_expression: "4 1 * * *"
  - name: KL_SENSOR_RESOURCES
    cron_expression: "5 1 * * *"
  - name: KL_GEO_RESOURCES
    cron_expression: "6 1 * * *"
  - name: KL_GEO_WFS
    cron_expression: "8 1 * * *"
  - name: OSM
    cron_expression: "10 1 * * *"
  - name: WIKIPEDIA
    cron_expression: "30 1 * * *"
  - name: EMERGENCY_POINTS
    cron_expression: "0 2 1 * *"
  - name: EV_STATIONS
    cron_expression: "10 2 1 * *"
  - name: VRN
    cron_expression: "20 2 1 * *"