# Generated by Django 5.1.15 on 2026-02-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lautrer_wissen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klcitydistrict',
            name='official_district_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
