# Generated by Django 5.1.15 on 2026-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lautrer_wissen', '0002_klcitydistrict_official_district_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographicdata',
            old_name='number',
            new_name='population_count',
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='age_group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='city_district_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='gender',
            field=models.CharField(max_length=255),
        ),
    ]
