# Generated by Django 5.1.15 on 2026-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lautrer_wissen', '0003_rename_number_demographicdata_population_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicdata',
            name='data_acquisition_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='data_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='insert_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
