# Generated by Django 5.1.15 on 2026-02-10 09:13

import django.db.models.deletion
import pipeline_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EVENTS_MIADI', 'Veranstaltungen (MIADI) Import'), ('EVENTS_WGA', 'Veranstaltungen (Was Geht App?) Import'), ('EVENTS_RIS', 'Ratsveranstaltungen (RSS) Import'), ('EXTERNAL_GEO_RESOURCES', 'Geodaten Import'), ('EV_STATIONS', 'E-Ladestationen Import'), ('GEO_WFS', 'Geodaten WFS Import'), ('MQTT_SENSOR_RESOURCES', 'Sensor (MQTT) Import'), ('WIFI_FREIFUNK', 'Wifi Freifunk Import'), ('WIFI_LOCAL', 'Wifi (lokale Daten) Import'), ('VRN', 'VRN Haltestellen Import'), ('OSM', 'Open Street Map Import'), ('WIKIPEDIA', 'Wikipedia Import'), ('EMERGENCY_POINTS', 'Rettungspunkte Import'), ('TTN_GATEWAY', 'TTN Gateway Import')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=200)),
                ('log_file', models.FileField(blank=True, null=True, upload_to='pipeline_logs/')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('cronjob', 'Cron/APSscheduler'), ('docker', 'Docker/CLI')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EVENTS_MIADI', 'Veranstaltungen (MIADI) Import'), ('EVENTS_WGA', 'Veranstaltungen (Was Geht App?) Import'), ('EVENTS_RIS', 'Ratsveranstaltungen (RSS) Import'), ('EXTERNAL_GEO_RESOURCES', 'Geodaten Import'), ('EV_STATIONS', 'E-Ladestationen Import'), ('GEO_WFS', 'Geodaten WFS Import'), ('MQTT_SENSOR_RESOURCES', 'Sensor (MQTT) Import'), ('WIFI_FREIFUNK', 'Wifi Freifunk Import'), ('WIFI_LOCAL', 'Wifi (lokale Daten) Import'), ('VRN', 'VRN Haltestellen Import'), ('OSM', 'Open Street Map Import'), ('WIKIPEDIA', 'Wikipedia Import'), ('EMERGENCY_POINTS', 'Rettungspunkte Import'), ('TTN_GATEWAY', 'TTN Gateway Import')], max_length=255, unique=True)),
                ('cron_expression', models.CharField(help_text="e.g. '0 2 * * *' for daily at 2AM", max_length=100, validators=[pipeline_manager.models.validate_cron_expression])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('filename', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EVResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('city_filter', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyPointResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('source_filename', models.CharField(max_length=255)),
                ('region_filter', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ep_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineRunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline_manager.pipelinerun')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RemoteResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceOSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=dict)),
                ('filename', models.CharField(max_length=255)),
                ('place_filter', models.CharField(max_length=255, null=True)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osm_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceWFSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('srs_name', models.CharField(max_length=100)),
                ('layer_name', models.CharField(max_length=100)),
                ('out_format', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('version', models.CharField(default='2.0.0', max_length=50, null=True)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfs_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceWikipage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('page_name', models.CharField(max_length=255)),
                ('table_indices', models.JSONField(default=list)),
                ('table_filenames', models.JSONField(default=list)),
                ('table_extractor_classes', models.JSONField(default=list)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikipage_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VRNResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('source_filename', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vrn_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WGAResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=255)),
                ('db_model_class', models.CharField(max_length=255)),
                ('db_model_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('region_latitude', models.CharField(max_length=255)),
                ('region_longitude', models.CharField(max_length=255)),
                ('region_region', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wga_resources', to='pipeline_manager.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
