# Generated by Django 5.1.15 on 2026-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteresourcefile',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='remoteresourcefile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LocalResourceFile',
        ),
    ]
