# Generated by Django 5.1.15 on 2026-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_manager', '0002_remoteresourcefile_local_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypointresourcefile',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evresourcefile',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vrnresourcefile',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wgaresourcefile',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
