# Generated by Django 5.1.15 on 2026-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_manager', '0003_emergencypointresourcefile_local_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(choices=[('EVENTS_MIADI', 'Veranstaltungen (MIADI) Import'), ('EVENTS_WGA', 'Veranstaltungen (Was Geht App?) Import'), ('EVENTS_RIS', 'Ratsveranstaltungen (RSS) Import'), ('EXTERNAL_GEO_RESOURCES', 'Geodaten Import'), ('EV_STATIONS', 'E-Ladestationen Import'), ('GEO_WFS', 'Geodaten WFS Import'), ('MQTT_SENSOR_RESOURCES', 'Sensor (MQTT) Import'), ('WIFI_FREIFUNK', 'Wifi Freifunk Import'), ('WIFI_LOCAL', 'Wifi (lokale Daten) Import'), ('VRN', 'VRN Haltestellen Import'), ('OSM', 'Open Street Map Import'), ('WIKIPEDIA', 'Wikipedia Import'), ('EMERGENCY_POINTS', 'Rettungspunkte Import'), ('TTN_GATEWAY', 'TTN Gateway Import'), ('DEMOGRAPHICS', 'Demografische Daten Import')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pipelineschedule',
            name='name',
            field=models.CharField(choices=[('EVENTS_MIADI', 'Veranstaltungen (MIADI) Import'), ('EVENTS_WGA', 'Veranstaltungen (Was Geht App?) Import'), ('EVENTS_RIS', 'Ratsveranstaltungen (RSS) Import'), ('EXTERNAL_GEO_RESOURCES', 'Geodaten Import'), ('EV_STATIONS', 'E-Ladestationen Import'), ('GEO_WFS', 'Geodaten WFS Import'), ('MQTT_SENSOR_RESOURCES', 'Sensor (MQTT) Import'), ('WIFI_FREIFUNK', 'Wifi Freifunk Import'), ('WIFI_LOCAL', 'Wifi (lokale Daten) Import'), ('VRN', 'VRN Haltestellen Import'), ('OSM', 'Open Street Map Import'), ('WIKIPEDIA', 'Wikipedia Import'), ('EMERGENCY_POINTS', 'Rettungspunkte Import'), ('TTN_GATEWAY', 'TTN Gateway Import'), ('DEMOGRAPHICS', 'Demografische Daten Import')], max_length=255, unique=True),
        ),
    ]
