# Generated by Django 5.1.15 on 2026-02-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'NGINX Dashboard',
                'verbose_name_plural': 'NGINX Analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DockerContainerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('log_file', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Docker Containers',
                'verbose_name_plural': 'Docker Containers',
                'managed': True,
            },
        ),
    ]
